### ISSUE TITLE
General NgRest Thread

### ISSUE THREAD

**Issue by nadar** [luyadev/luya#417]
+ [x] ability to group fields #234 
+ [ ] required fields informations from AR Model #275 
+ [ ] ability to add javascript (toggling) inside forms #278 
+ [x] default sort parameter #333
+ [ ] ngRest config class (from ideas pool) #335 
+ [ ] provide field length informations from AR model #394 
+ [x] add angular events `after` `before` to reload angular admin #593
